packages:
  - "apps/web"
allowBuilds:
  esbuild: true
overrides:
  valibot: 1.4.2
minimumReleaseAgeExclude:
  - framer-motion@13.1.1
  - motion-dom@13.1.1
  - motion@13.1.1
  - '@storybook/addon-a11y@10.5.10'
  - '@storybook/addon-docs@10.5.10'
  - '@storybook/addon-vitest@10.5.10'
  - '@storybook/builder-vite@10.5.10'
  - '@storybook/csf-plugin@10.5.10'
  - '@storybook/react-dom-shim@10.5.10'
  - '@storybook/react-vite@10.5.10'
  - '@storybook/react@10.5.10'
  - eslint-plugin-storybook@10.5.10
  - storybook@10.5.10
